import type { CatalogField, ProcessingCatalogEntry, ProcessingNodeKind, ProcessingRuntime } from "./types.js";
import { inPort, outPort, T } from "./ports.js";

function nodeKindFromRuntime(runtime: ProcessingRuntime): ProcessingNodeKind | undefined {
  switch (runtime) {
    case "core-block":
      return "block";
    case "core-rule":
      return "rule";
    case "core-schedule":
      return "schedule";
    case "core-event":
      return "event-source";
    default:
      return undefined;
  }
}

function e(entry: Omit<ProcessingCatalogEntry, "nodeKind">): ProcessingCatalogEntry {
  return { ...entry, nodeKind: nodeKindFromRuntime(entry.runtime) };
}

const AUTHORING = "Authoring visibile sul blocco; il Config/firmware si aggancia in un passo successivo.";

/** Firmware entry-point: Schedule / Event emit jolly `activation` to start a chain. */
const ENTRY_OUTPUTS = [outPort("0", [T.activationTrigger, T.eventTrigger], "Attivazione")];

function sel(id: string, label: string, options: readonly { value: string; label: string }[], def?: string): CatalogField {
  return { id, label, type: "select", options, default: def };
}
function num(id: string, label: string, def?: number, placeholder?: string): CatalogField {
  return { id, label, type: "number", default: def, placeholder };
}
function chk(id: string, label: string, def = false): CatalogField {
  return { id, label, type: "checkbox", default: def, placeholder: label };
}
function txt(id: string, label: string, def?: string, placeholder?: string): CatalogField {
  return { id, label, type: "text", default: def, placeholder };
}
function area(id: string, label: string, placeholder?: string): CatalogField {
  return { id, label, type: "textarea", placeholder };
}

/**
 * AppBlocks Library operations that have a SpaghettiLAB analog, plus native
 * Block Drivers. Named `fields` are the authoring surface on the block;
 * Config/firmware mapping comes later. Vendor-only hardware is omitted.
 */
export const PROCESSING_BLOCK_CATALOG: readonly ProcessingCatalogEntry[] = [
  e({
    id: "native.schedule",
    label: "Schedule",
    subtitle: "Campionamento periodico",
    category: "trigger",
    runtime: "core-schedule",
    availability: "shipped",
    family: "functionality",
    inputs: [],
    outputs: ENTRY_OUTPUTS,
    notes:
      "Entry point firmware (`spaghetti_runtime_schedule_config`): a ogni periodo emette attivazione (jolly). Equivalente AppBlocks: On Time Period. Se disabilitato non viene eseguito.",
  }),
  e({
    id: "native.event-source",
    label: "Event source",
    subtitle: "Record asincroni",
    category: "trigger",
    runtime: "core-event",
    availability: "shipped",
    inputs: [],
    outputs: ENTRY_OUTPUTS,
    notes: "Entry point firmware: Module che pubblica eventi (`spaghetti_module_manager_start_events`). Output = attivazione (jolly).",
  }),
  e({
    id: "native.flow_start",
    label: "Attivazione",
    subtitle: "Pallino Schedule → primo blocco",
    category: "trigger",
    runtime: "core-block",
    availability: "shipped",
    typeId: "ab.flow_start",
    needsModule: false,
    inputs: [],
    outputs: [outPort("0", [T.activationTrigger], "Attivazione")],
    notes:
      "Pallino violetto fisso dentro ogni Schedule (non dalla palette). Solo uscita a destra: collega al Digital Toggle o a un altro blocco per scegliere l’entry.",
  }),
  e({
    id: "appblocks.system",
    label: "On Boot",
    subtitle: "All'avvio del Core",
    category: "system",
    runtime: "core-event",
    availability: "planned",
    appblocksId: "system",
    needsModule: false,
    inputs: [],
    outputs: ENTRY_OUTPUTS,
    notes: AUTHORING,
  }),
  e({
    id: "appblocks.debug",
    label: "Debug Print",
    subtitle: "Log di debug",
    category: "system",
    runtime: "core-block",
    availability: "planned",
    appblocksId: "debug",
    typeId: "ab.debug",
    fields: [area("message", "Messaggio", "testo da stampare")],
    notes: AUTHORING,
  }),
  e({
    id: "appblocks.label",
    label: "Comment",
    subtitle: "Nota di authoring",
    category: "system",
    runtime: "core-block",
    availability: "planned",
    appblocksId: "label",
    typeId: "ab.comment",
    fields: [area("text", "Commento")],
    notes: AUTHORING,
  }),
  e({
    id: "appblocks.system_reboot",
    label: "System Reboot",
    subtitle: "Riavvio Core",
    category: "system",
    runtime: "core-block",
    availability: "planned",
    appblocksId: "system_reboot",
    typeId: "ab.system_reboot",
    fields: [num("delayMs", "Ritardo (ms)", 0)],
    notes: AUTHORING,
  }),
  e({
    id: "appblocks.upgrade_firmware",
    label: "Upgrade Firmware",
    subtitle: "OTA via HTTP",
    category: "system",
    runtime: "core-block",
    availability: "planned",
    appblocksId: "upgrade_firmware",
    typeId: "ab.upgrade_firmware",
    fields: [txt("url", "URL file TCU", "", "https://…")],
    notes: AUTHORING,
  }),

  e({
    id: "appblocks.variable_changed",
    label: "On Variable Changed",
    subtitle: "Cambio variabile",
    category: "variables",
    runtime: "core-event",
    availability: "planned",
    appblocksId: "variable_changed",
    needsModule: false,
    fields: [txt("variable", "Variabile")],
    notes: AUTHORING,
  }),
  e({
    id: "appblocks.variable_set",
    label: "Variable Set/Math",
    subtitle: "Scrivi variabile",
    category: "variables",
    runtime: "core-block",
    availability: "planned",
    appblocksId: "variable_set",
    typeId: "ab.variable_set",
    fields: [
      txt("variable", "Variabile"),
      sel("op", "Operazione", [
        { value: "set", label: "=" },
        { value: "add", label: "+=" },
        { value: "sub", label: "-=" },
        { value: "mul", label: "×=" },
        { value: "div", label: "÷=" },
      ], "set"),
      txt("value", "Valore"),
    ],
    notes: AUTHORING,
  }),

  e({
    id: "appblocks.command_triggered",
    label: "On Command Triggered",
    subtitle: "Evento comando",
    category: "logic",
    runtime: "core-event",
    availability: "planned",
    appblocksId: "command_triggered",
    needsModule: false,
    fields: [txt("command", "Comando")],
    notes: AUTHORING,
  }),
  e({
    id: "appblocks.comparison",
    label: "IF Condition",
    subtitle: "Soglia booleana",
    category: "logic",
    runtime: "core-block",
    availability: "shipped",
    appblocksId: "comparison",
    typeId: "threshold",
    fields: [
      sel("op", "Operatore", [
        { value: "eq", label: "=" },
        { value: "neq", label: "≠" },
        { value: "gt", label: ">" },
        { value: "lt", label: "<" },
        { value: "gte", label: "≥" },
        { value: "lte", label: "≤" },
      ], "gte"),
      { id: "1", label: "Valore", type: "number", default: 0 },
    ],
    notes: "Il grafo Core è un DAG: `threshold` emette un bool. L'operatore è authoring; il firmware oggi applica ≥ sul field 1.",
  }),
  e({
    id: "appblocks.compound_condition",
    label: "IF Compound Condition",
    subtitle: "Più confronti",
    category: "logic",
    runtime: "core-block",
    availability: "planned",
    appblocksId: "compound_condition",
    typeId: "ab.compound_condition",
    fields: [
      sel("combinator", "Combinatore", [
        { value: "and", label: "AND" },
        { value: "or", label: "OR" },
      ], "and"),
      area("expression", "Confronti", "es. temp > 20 AND umidità < 80"),
    ],
    notes: AUTHORING,
  }),
  e({
    id: "appblocks.switch",
    label: "Switch",
    subtitle: "Seleziona un ingresso",
    category: "logic",
    runtime: "core-block",
    availability: "shipped",
    appblocksId: "switch",
    typeId: "select",
    notes: "Block firmware `select`.",
  }),
  e({
    id: "appblocks.forloop",
    label: "For Loop",
    subtitle: "Ripeti N volte",
    category: "logic",
    runtime: "core-block",
    availability: "planned",
    appblocksId: "forloop",
    typeId: "ab.forloop",
    fields: [num("from", "Da", 0), num("to", "A", 10), num("step", "Passo", 1)],
    notes: AUTHORING,
  }),
  e({
    id: "appblocks.command_trigger",
    label: "Execute Command",
    subtitle: "Esegui un comando",
    category: "logic",
    runtime: "core-block",
    availability: "planned",
    appblocksId: "command_trigger",
    typeId: "ab.execute_command",
    fields: [txt("command", "Comando"), txt("argument", "Argomento", "")],
    notes: AUTHORING,
  }),

  e({
    id: "appblocks.arithmetic",
    label: "Calculate",
    subtitle: "Addizione (cambia type_id per − × ÷)",
    category: "math",
    runtime: "core-block",
    availability: "shipped",
    appblocksId: "arithmetic",
    typeId: "add",
    fields: [
      sel("op", "Operazione", [
        { value: "add", label: "+" },
        { value: "sub", label: "−" },
        { value: "mul", label: "×" },
        { value: "div", label: "÷" },
      ], "add"),
      txt("b", "Secondo operando", "", "valore o variabile"),
    ],
    notes: "Firmware: Block `add` (e subtract/multiply/divide in palette). L'operatore è visibile in authoring.",
  }),
  e({
    id: "block.subtract",
    label: "Subtract",
    subtitle: "a − b",
    category: "math",
    runtime: "core-block",
    availability: "shipped",
    typeId: "subtract",
    notes: "Block firmware `subtract`.",
  }),
  e({
    id: "block.multiply",
    label: "Multiply",
    subtitle: "a × b",
    category: "math",
    runtime: "core-block",
    availability: "shipped",
    typeId: "multiply",
    notes: "Block firmware `multiply`.",
  }),
  e({
    id: "block.divide",
    label: "Divide",
    subtitle: "a ÷ b",
    category: "math",
    runtime: "core-block",
    availability: "shipped",
    typeId: "divide",
    notes: "Block firmware `divide`. Overflow/divisione per zero = errore bounded, non NaN silenzioso.",
  }),
  e({
    id: "appblocks.bitwise",
    label: "Bitwise",
    subtitle: "Mask e shift",
    category: "math",
    runtime: "core-block",
    availability: "shipped",
    appblocksId: "bitwise",
    typeId: "mask_shift",
    fields: [
      sel("op", "Operazione", [
        { value: "and", label: "AND" },
        { value: "or", label: "OR" },
        { value: "xor", label: "XOR" },
        { value: "not", label: "NOT" },
        { value: "shl", label: "Shift left" },
        { value: "shr", label: "Shift right" },
      ], "and"),
      txt("operand", "Operando", "", "mask / shift"),
    ],
    notes: "Block firmware `mask_shift`. Operazione visibile in authoring.",
  }),
  e({
    id: "appblocks.math_compound",
    label: "Custom Function",
    subtitle: "Polinomio bounded",
    category: "math",
    runtime: "core-block",
    availability: "shipped",
    appblocksId: "math_compound",
    typeId: "polynomial",
    fields: [area("formula", "Formula", "es. 2x^2 + 3x + 1")],
    notes: "Firmware: Block `polynomial`. La formula è authoring visibile sul blocco.",
  }),
  e({
    id: "appblocks.random",
    label: "Random",
    subtitle: "Valore casuale",
    category: "math",
    runtime: "core-block",
    availability: "planned",
    appblocksId: "random",
    typeId: "random",
    notes: "Driver `random` ancora da scrivere; il grafo si può già autorare con questo type_id.",
  }),
  e({
    id: "block.scale_offset",
    label: "Scale / offset",
    subtitle: "in × scale + offset",
    category: "math",
    runtime: "core-block",
    availability: "shipped",
    typeId: "scale_offset",
    notes: "Block firmware nativo, senza gemello AppBlocks.",
  }),
  e({
    id: "block.clamp",
    label: "Clamp",
    subtitle: "Satura in [min, max]",
    category: "math",
    runtime: "core-block",
    availability: "shipped",
    typeId: "clamp",
    notes: "Block firmware nativo.",
  }),
  e({
    id: "block.map_range",
    label: "Map range",
    subtitle: "Rimappa un intervallo",
    category: "math",
    runtime: "core-block",
    availability: "shipped",
    typeId: "map_range",
    notes: "Block firmware nativo.",
  }),
  e({
    id: "block.unit_convert",
    label: "Unit convert",
    subtitle: "Conversione unità",
    category: "math",
    runtime: "core-block",
    availability: "shipped",
    typeId: "unit_convert",
    notes: "Block firmware nativo. Le conversioni restano nodi espliciti, mai implicite sull'edge.",
  }),
  e({
    id: "block.combine_fields",
    label: "Combine fields",
    subtitle: "Unisci campi",
    category: "math",
    runtime: "core-block",
    availability: "shipped",
    typeId: "combine_fields",
    notes: "Block firmware nativo.",
  }),

  e({
    id: "block.moving_average",
    label: "Moving average",
    subtitle: "Media mobile",
    category: "filter",
    runtime: "core-block",
    availability: "shipped",
    typeId: "moving_average",
    notes: "Block firmware nativo (pack processing-basic).",
  }),
  e({
    id: "block.low_pass",
    label: "Low pass",
    subtitle: "Passa-basso",
    category: "filter",
    runtime: "core-block",
    availability: "shipped",
    typeId: "low_pass",
    notes: "Block firmware nativo.",
  }),
  e({
    id: "block.median",
    label: "Median",
    subtitle: "Filtro mediano",
    category: "filter",
    runtime: "core-block",
    availability: "shipped",
    typeId: "median",
    notes: "Block firmware nativo.",
  }),
  e({
    id: "block.hysteresis",
    label: "Hysteresis",
    subtitle: "Soglia con isteresi",
    category: "filter",
    runtime: "core-block",
    availability: "shipped",
    typeId: "hysteresis",
    notes: "Block firmware nativo.",
  }),
  e({
    id: "block.debounce",
    label: "Debounce",
    subtitle: "Antirimbalzo",
    category: "filter",
    runtime: "core-block",
    availability: "shipped",
    typeId: "debounce",
    notes: "Block firmware nativo.",
  }),
  e({
    id: "block.kalman",
    label: "Kalman",
    subtitle: "Filtro 1D",
    category: "filter",
    runtime: "core-block",
    availability: "pack",
    typeId: "kalman",
    packId: "processing-kalman",
    notes: "Capability Pack `processing-kalman`, non nell'immagine minima.",
  }),

  e({
    id: "appblocks.timer_completed",
    label: "On Timer Completed",
    subtitle: "Timer scaduto",
    category: "time",
    runtime: "core-event",
    availability: "planned",
    appblocksId: "timer_completed",
    needsModule: false,
    fields: [txt("timer", "Timer")],
    notes: AUTHORING,
  }),
  e({
    id: "appblocks.time_interval",
    label: "On Time Period",
    subtitle: "Intervallo periodico",
    category: "time",
    runtime: "core-event",
    availability: "planned",
    appblocksId: "time_interval",
    needsModule: false,
    fields: [num("periodSec", "Periodo (s)", 1)],
    notes: AUTHORING,
  }),
  e({
    id: "appblocks.cron_event",
    label: "On Scheduled Event",
    subtitle: "Scheduler / cron",
    category: "time",
    runtime: "core-event",
    availability: "planned",
    appblocksId: "cron_event",
    needsModule: false,
    fields: [txt("schedule", "Pianificazione", "", "es. 0 8 * * *")],
    notes: AUTHORING,
  }),
  e({
    id: "appblocks.timer_start",
    label: "Timer Start",
    subtitle: "Avvia timer",
    category: "time",
    runtime: "core-block",
    availability: "planned",
    appblocksId: "timer_start",
    typeId: "ab.timer_start",
    fields: [txt("timer", "Timer"), num("durationSec", "Durata (s)", 1)],
    notes: AUTHORING,
  }),
  e({
    id: "appblocks.timer_stop",
    label: "Timer Stop",
    subtitle: "Ferma timer",
    category: "time",
    runtime: "core-block",
    availability: "planned",
    appblocksId: "timer_stop",
    typeId: "ab.timer_stop",
    fields: [txt("timer", "Timer")],
    notes: AUTHORING,
  }),
  e({
    id: "appblocks.time_delay",
    label: "Delay",
    subtitle: "Ritardo",
    category: "time",
    runtime: "core-block",
    availability: "planned",
    appblocksId: "time_delay",
    typeId: "ab.delay",
    fields: [num("seconds", "Secondi", 1)],
    notes: AUTHORING,
  }),
  e({
    id: "appblocks.datetime",
    label: "Get Current DateTime",
    subtitle: "Orologio",
    category: "time",
    runtime: "core-block",
    availability: "planned",
    appblocksId: "datetime",
    typeId: "ab.get_datetime",
    fields: [txt("variable", "Salva in variabile", "")],
    notes: AUTHORING,
  }),
  e({
    id: "appblocks.datetime_format",
    label: "Format DateTime",
    subtitle: "Formatta data/ora",
    category: "time",
    runtime: "core-block",
    availability: "planned",
    appblocksId: "datetime_format",
    typeId: "ab.datetime_format",
    fields: [txt("source", "Sorgente"), txt("format", "Formato", "YYYY-MM-DD HH:mm:ss")],
    notes: AUTHORING,
  }),

  e({
    id: "appblocks.keypad",
    label: "On Button Pressed",
    subtitle: "Fronte pulsante",
    category: "io",
    runtime: "core-event",
    availability: "unavailable",
    appblocksId: "keypad",
    notes: "Escluso da questa passata di authoring.",
  }),
  e({
    id: "appblocks.keypad_released",
    label: "On Button Released",
    subtitle: "Rilascio pulsante",
    category: "io",
    runtime: "core-event",
    availability: "unavailable",
    appblocksId: "keypad_released",
    notes: "Escluso da questa passata di authoring.",
  }),
  e({
    id: "appblocks.interrupt",
    label: "On Interrupt",
    subtitle: "GPIO interrupt",
    category: "io",
    runtime: "core-event",
    availability: "shipped",
    appblocksId: "interrupt",
    fields: [txt("line", "Linea / pin", "")],
    notes: "Event source su Module GPIO. La linea è authoring visibile sul blocco.",
  }),
  e({
    id: "appblocks.digital_line_set",
    label: "Digital Line Set",
    subtitle: "Scrivi GPIO HIGH/LOW",
    category: "io",
    runtime: "core-block",
    availability: "shipped",
    appblocksId: "digital_line_set",
    typeId: "ab.digital_line_set",
    fields: [
      txt("line", "Linea", "LED"),
      sel("state", "Stato", [
        { value: "high", label: "HIGH" },
        { value: "low", label: "LOW" },
      ], "high"),
    ],
    notes: AUTHORING,
  }),
  e({
    id: "appblocks.digital_out_toggle",
    label: "Digital Toggle",
    subtitle: "Inverti uscita digitale",
    category: "io",
    runtime: "core-block",
    availability: "shipped",
    family: "functionality",
    appblocksId: "digital_out_toggle",
    typeId: "ab.digital_out_toggle",
    inputs: [
      inPort("0", [T.activationTrigger, T.eventTrigger, T.digitalComando], {
        label: "Trigger / comando",
        required: true,
      }),
    ],
    outputs: [outPort("0", [T.digitalComando], "Comando digitale")],
    fields: [
      txt("line", "Linea", "LED"),
      sel(
        "toggleMode",
        "Tipo di toggle",
        [
          { value: "astable", label: "Astable (toggle a ogni impulso)" },
          { value: "pulse_high", label: "Impulso HIGH (riposo LOW)" },
          { value: "pulse_low", label: "Impulso LOW (riposo HIGH)" },
        ],
        "astable",
      ),
      {
        ...sel("initial", "Stato iniziale", [
          { value: "high", label: "ON (dopo rising edge)" },
          { value: "low", label: "OFF (dopo falling edge)" },
        ], "high"),
        when: { field: "toggleMode", equals: "astable" },
      },
      {
        ...num(
          "lowToHigh",
          "Contatore impulsi ON",
          1,
          "Quanti trigger Schedule (impulsi) restare OFF prima del rising edge / ON",
        ),
        when: { field: "toggleMode", equals: "astable" },
      },
      {
        ...num(
          "highToLow",
          "Contatore impulsi OFF",
          1,
          "Quanti trigger Schedule (impulsi) restare ON prima del falling edge / OFF",
        ),
        when: { field: "toggleMode", equals: "astable" },
      },
      {
        ...num(
          "pulseMs",
          "Durata impulso (ms)",
          100,
          "Larghezza dell’impulso dopo ogni trigger Schedule",
        ),
        when: { field: "toggleMode", in: ["pulse_high", "pulse_low"] },
      },
    ],
    notes:
      "Input: attivazione dallo Start (o jolly da Schedule). Output: comando digitale (0/1). Astabile = cambia stato a ogni impulso; impulso HIGH/LOW = monostabile (riposo + impulso sulla durata impostata).",
  }),
  e({
    id: "appblocks.compare_if",
    label: "IF",
    subtitle: "Confronto → comando",
    category: "logic",
    runtime: "core-block",
    availability: "shipped",
    family: "functionality",
    appblocksId: "compare_if",
    typeId: "ab.compare_if",
    needsModule: false,
    inputs: [
      inPort("0", [T.digitalComando, T.analogMisura], {
        label: "Ingresso",
        required: true,
      }),
    ],
    outputs: [outPort("0", [T.digitalComando], "Uscita")],
    fields: [
      sel(
        "compare",
        "Quando",
        [
          { value: "eq", label: "è uguale" },
          { value: "neq", label: "è diverso" },
          { value: "gt", label: "è maggiore" },
          { value: "gte", label: "è maggiore o uguale" },
          { value: "lt", label: "è minore" },
          { value: "lte", label: "è minore o uguale" },
        ],
        "eq",
      ),
      sel(
        "compareLevel",
        "Livello",
        [
          { value: "high", label: "HIGH" },
          { value: "low", label: "LOW" },
        ],
        "high",
      ),
      num("compareTempC", "Temperatura (°C)", 25, "Soglia in °C"),
      sel(
        "inputType",
        "Tipo di ingresso",
        [
          { value: "digital", label: "Digitale" },
          { value: "analog", label: "Analogico" },
        ],
        "digital",
      ),
      sel(
        "outputType",
        "Tipo di uscita",
        [
          { value: "digital", label: "Digitale" },
          { value: "boolean", label: "Booleano" },
        ],
        "digital",
      ),
      sel(
        "thenOutput",
        "allora uscita",
        [
          { value: "high", label: "HIGH" },
          { value: "low", label: "LOW" },
        ],
        "high",
      ),
      sel(
        "elseOutput",
        "altrimenti",
        [
          { value: "high", label: "HIGH" },
          { value: "low", label: "LOW" },
        ],
        "low",
      ),
    ],
    notes:
      "Un solo ingresso alla volta: Digital Toggle (uguale / diverso da HIGH/LOW) oppure Sensore temperatura (uguale / diverso / maggiore / minore). Tipo di uscita: Digitale (HIGH/LOW, può comandare LED o Relè) oppure Booleano (true/false, non è un ingresso digitale/analogico).",
  }),
  e({
    id: "appblocks.led",
    label: "LED",
    subtitle: "Indicatore luminoso",
    category: "io",
    runtime: "core-block",
    availability: "shipped",
    family: "bay",
    bayIo: "output",
    bayFamilyId: "bay.led",
    appblocksId: "led",
    typeId: "ab.led",
    needsModule: false,
    inputs: [
      inPort("0", [T.digitalComando, T.analogComando], {
        label: "Comando",
        required: true,
      }),
    ],
    outputs: [],
    fields: [
      { id: "color", label: "Colore", type: "color", default: "#F5C518" },
      num("threshold", "Soglia (0–100)", 50, "Accende se il comando ≥ soglia"),
      chk("negated", "Negato", false),
      num(
        "delayOnMs",
        "Ritardo ON (ms)",
        0,
        "Attesa dopo il segnale ON (comando ≥ soglia) prima di soft start",
      ),
      num(
        "delayOffMs",
        "Ritardo OFF (ms)",
        0,
        "Attesa dopo il segnale OFF (comando < soglia) prima di soft stop",
      ),
      num("softOnMs", "Soft start ON (ms)", 0, "Velocità di salita 0→100% (0 = istantaneo)"),
      num("softOffMs", "Soft stop OFF (ms)", 0, "Velocità di decadimento 100%→0 (0 = istantaneo)"),
    ],
    notes:
      "Sink su comando digitale (0/100) o analogico (0–100). Acceso se livello ≥ soglia. Ritardi ON/OFF rispetto al segnale, poi soft start/stop.",
  }),
  e({
    id: "appblocks.rgb_led",
    label: "RGB LED",
    subtitle: "Sequenze colore · trigger in ingresso",
    category: "io",
    runtime: "core-block",
    availability: "planned",
    family: "bay",
    bayIo: "output",
    bayFamilyId: "bay.rgb_led",
    appblocksId: "rgb_led",
    typeId: "ab.rgb_led",
    needsModule: false,
    inputs: [
      inPort("0", [T.activationTrigger, T.eventTrigger, T.digitalComando], {
        label: "Trigger",
        required: true,
      }),
    ],
    outputs: [],
    fields: [
      sel(
        "mode",
        "Modalità",
        [
          { value: "preset", label: "Effetto pronto" },
          { value: "sequence", label: "Sequenza mia" },
        ],
        "preset",
      ),
      sel(
        "triggerEdge",
        "Trigger",
        [
          { value: "rising", label: "Rising edge" },
          { value: "falling", label: "Falling edge" },
        ],
        "rising",
      ),
      sel(
        "triggerAction",
        "Azione sul trigger",
        [
          {
            value: "follow",
            label: "Segue il trigger (stop sul bordo opposto)",
          },
          {
            value: "start",
            label: "Avvia e non ferma sul bordo opposto",
          },
        ],
        "follow",
      ),
      {
        ...sel(
          "preset",
          "Effetto",
          [
            { value: "solid", label: "Solid" },
            { value: "breathe", label: "Breathe" },
            { value: "blink", label: "Blink" },
            { value: "color_cycle", label: "Color cycle" },
          ],
          "solid",
        ),
        when: { field: "mode", equals: "preset" },
      },
      {
        id: "color",
        label: "Colore",
        type: "color",
        default: "#FF3366",
        when: { field: "preset", in: ["solid", "breathe", "blink"] },
      },
      {
        ...num("intensity", "Intensità (0–100)", 100),
        when: { field: "mode", equals: "preset" },
      },
      {
        ...num("speedMs", "Velocità / periodo (ms)", 1200, "Breathe, blink, color cycle"),
        when: { field: "preset", in: ["breathe", "blink", "color_cycle"] },
      },
      chk("loop", "Loop", true),
      num("ledCount", "N LED (stub bay)", 1, "Dal bay/NFC quando disponibile"),
    ],
    notes:
      AUTHORING +
      " Player di sequenze: rising/falling sceglie il bordo che avvia. «Segue il trigger» spegne sul bordo opposto; «Avvia e non ferma» lascia correre la sequenza. Effetti pronti = sequenze parametriche; in «Sequenza mia» componi solid/fade/wait. Strip (N LED) = un unico player.",
  }),
  e({
    id: "appblocks.relay",
    label: "Relay",
    subtitle: "Uscita relè",
    category: "io",
    runtime: "core-block",
    availability: "planned",
    family: "bay",
    bayIo: "output",
    bayFamilyId: "bay.relay",
    appblocksId: "relay",
    typeId: "ab.relay",
    needsModule: false,
    inputs: [
      inPort("0", [T.digitalComando], {
        label: "Comando",
        required: true,
      }),
    ],
    outputs: [],
    fields: [
      txt("line", "Linea", "RELAY"),
      sel(
        "closeWhen",
        "Chiuso quando l'ingresso è",
        [
          { value: "high", label: "HIGH" },
          { value: "low", label: "LOW" },
        ],
        "high",
      ),
    ],
    notes: AUTHORING + " Relè hardware: chiuso se l’ingresso è HIGH, oppure chiuso se l’ingresso è LOW.",
  }),
  e({
    id: "appblocks.temperature_sensor",
    label: "Sensore temperatura",
    subtitle: "Misura in °C",
    category: "io",
    runtime: "core-block",
    availability: "shipped",
    family: "bay",
    bayIo: "input",
    bayFamilyId: "bay.temperature_sensor",
    appblocksId: "temperature_sensor",
    typeId: "ab.temperature_sensor",
    needsModule: false,
    inputs: [],
    outputs: [outPort("0", [T.analogMisura], "Temperatura")],
    fields: [num("testC", "Temperatura di prova (°C)", 22, "Valore per il dry-run")],
    notes: AUTHORING + " Sensore hardware: si collega solo a un blocco IF. L’indicatore sotto il blocco serve a provare la temperatura.",
  }),
  e({
    id: "appblocks.terminal_block",
    label: "Terminal block",
    subtitle: "6 canali digital / analog / alimentazione",
    category: "io",
    runtime: "core-block",
    availability: "planned",
    family: "bay",
    bayIo: "input",
    bayFamilyId: "bay.terminal_block",
    appblocksId: "terminal_block",
    typeId: "ab.terminal_block",
    needsModule: false,
    inputs: [],
    outputs: [1, 2, 3, 4, 5, 6].map((n) =>
      outPort(String(n - 1), [T.digitalMisura, T.analogMisura, T.powerMisura], `CH${n}`),
    ),
    fields: [1, 2, 3, 4, 5, 6].flatMap((n) => [
      txt(`ch${n}Name`, `Nome canale ${n}`, `CH${n}`, `Es. Sensore A`),
      sel(
        `ch${n}Mode`,
        `Tipo CH${n}`,
        [
          { value: "digital", label: "Digitale" },
          { value: "analog", label: "Analogico" },
          { value: "alimentazione", label: "Alimentazione" },
        ],
        "digital",
      ),
      chk(`ch${n}Enabled`, `Canale ${n} attivo`, true),
      {
        ...num(`ch${n}Voltage`, `Tensione CH${n} (V)`, 24, "Valore di alimentazione"),
        when: { field: `ch${n}Mode`, equals: "alimentazione" },
      },
      {
        ...sel(
          `ch${n}PowerDir`,
          `Direzione CH${n}`,
          [
            { value: "input", label: "Ingresso — alimentato dall'esterno" },
            { value: "output", label: "Uscita — alimento il device" },
          ],
          "input",
        ),
        when: { field: `ch${n}Mode`, equals: "alimentazione" },
      },
    ]),
    notes:
      AUTHORING +
      " Morsettiera bay: fino a 6 canali digital, analog o alimentazione (tensione + direzione ingresso/uscita). Nomi editabili; sul canvas ogni nome sta accanto al pallino.",
  }),

  e({
    id: "appblocks.num_round",
    label: "Number Round Decimal Points",
    subtitle: "Arrotonda",
    category: "strings",
    runtime: "core-block",
    availability: "planned",
    appblocksId: "num_round",
    typeId: "round",
    notes: "Driver `round` pianificato (valore numerico bounded, non formattazione stringa libera).",
  }),

  e({
    id: "appblocks.lcd_set_screen",
    label: "LCD Set Screen",
    subtitle: "Schermo LCD",
    category: "display",
    runtime: "core-block",
    availability: "planned",
    appblocksId: "lcd_set_screen",
    typeId: "ab.lcd_set_screen",
    fields: [txt("screen", "Schermata")],
    notes: AUTHORING,
  }),
  e({
    id: "appblocks.lcd_menu",
    label: "Enter LCD Menu",
    subtitle: "Menu LCD",
    category: "display",
    runtime: "core-block",
    availability: "planned",
    appblocksId: "lcd_menu",
    typeId: "ab.lcd_menu",
    fields: [txt("menu", "Menu", "")],
    notes: AUTHORING,
  }),
  e({
    id: "appblocks.lcd_text_widget",
    label: "LCD Text Widget",
    subtitle: "Testo LCD",
    category: "display",
    runtime: "core-block",
    availability: "planned",
    appblocksId: "lcd_text_widget",
    typeId: "ab.lcd_text_widget",
    fields: [txt("widget", "Widget"), area("text", "Testo"), sel("visible", "Visibilità", [{ value: "show", label: "Visibile" }, { value: "hide", label: "Nascosto" }], "show")],
    notes: AUTHORING,
  }),
  e({
    id: "appblocks.lcd_image_widget",
    label: "LCD Image Widget",
    subtitle: "Immagine LCD",
    category: "display",
    runtime: "core-block",
    availability: "planned",
    appblocksId: "lcd_image_widget",
    typeId: "ab.lcd_image_widget",
    fields: [txt("widget", "Widget"), txt("image", "Immagine")],
    notes: AUTHORING,
  }),
  e({
    id: "appblocks.lcd_graph_widget",
    label: "LCD Line Graph Add Point",
    subtitle: "Grafico LCD",
    category: "display",
    runtime: "out-of-scope",
    availability: "unavailable",
    appblocksId: "lcd_graph_widget",
    notes: "Nessun LCD sul Core. Un display è un altro Core/Module, collegato via Node-RED.",
  }),
  e({
    id: "appblocks.lcd_graph_widget_clear",
    label: "LCD Line Graph Clear",
    subtitle: "Pulisci grafico LCD",
    category: "display",
    runtime: "out-of-scope",
    availability: "unavailable",
    appblocksId: "lcd_graph_widget_clear",
    notes: "Nessun LCD sul Core. Un display è un altro Core/Module, collegato via Node-RED.",
  }),

  e({
    id: "appblocks.pat",
    label: "LED Pattern",
    subtitle: "Comando LED",
    category: "sound",
    runtime: "core-rule",
    availability: "unavailable",
    appblocksId: "pat",
    typeId: "threshold",
    notes: "Escluso da questa passata di authoring.",
  }),
  e({
    id: "appblocks.beep",
    label: "Buzzer Pattern",
    subtitle: "Comando buzzer",
    category: "sound",
    runtime: "core-rule",
    availability: "unavailable",
    appblocksId: "beep",
    typeId: "threshold",
    notes: "Escluso da questa passata di authoring.",
  }),

  e({
    id: "appblocks.table",
    label: "Table Lookup",
    subtitle: "Tabella bounded",
    category: "storage",
    runtime: "core-block",
    availability: "shipped",
    appblocksId: "table",
    typeId: "lookup_table",
    fields: [txt("table", "Tabella"), txt("key", "Chiave")],
    notes: "Block firmware `lookup_table`. Tabella/chiave visibili in authoring.",
  }),
  e({
    id: "appblocks.table_insert",
    label: "Table Insert Row",
    subtitle: "Inserisci riga",
    category: "storage",
    runtime: "core-block",
    availability: "planned",
    appblocksId: "table_insert",
    typeId: "ab.table_insert",
    fields: [txt("table", "Tabella"), area("values", "Valori", "colonne o JSON")],
    notes: AUTHORING,
  }),
  e({
    id: "appblocks.table_update",
    label: "Table Update Row",
    subtitle: "Aggiorna riga",
    category: "storage",
    runtime: "core-block",
    availability: "planned",
    appblocksId: "table_update",
    typeId: "ab.table_update",
    fields: [txt("table", "Tabella"), txt("key", "Chiave"), area("values", "Valori")],
    notes: AUTHORING,
  }),
  e({
    id: "appblocks.table_delete",
    label: "Table Delete Row",
    subtitle: "Elimina riga",
    category: "storage",
    runtime: "out-of-scope",
    availability: "unavailable",
    appblocksId: "table_delete",
    notes: "Niente tabelle mutabili unbounded sul Core.",
  }),
  e({
    id: "appblocks.table_clear",
    label: "Clear Table",
    subtitle: "Svuota tabella",
    category: "storage",
    runtime: "out-of-scope",
    availability: "unavailable",
    appblocksId: "table_clear",
    notes: "Niente tabelle mutabili unbounded sul Core.",
  }),
  e({
    id: "appblocks.table_row_count",
    label: "Table Row Count",
    subtitle: "Conteggio righe",
    category: "storage",
    runtime: "out-of-scope",
    availability: "unavailable",
    appblocksId: "table_row_count",
    notes: "La lookup firmware ha dimensione fissa nel Config, non un count dinamico.",
  }),
  e({
    id: "appblocks.log_add",
    label: "Add to Log",
    subtitle: "Log eventi",
    category: "storage",
    runtime: "core-block",
    availability: "planned",
    appblocksId: "log_add",
    typeId: "ab.log_add",
    fields: [area("message", "Voce di log")],
    notes: AUTHORING,
  }),
  e({
    id: "appblocks.settings_init",
    label: "Settings Init",
    subtitle: "Init / factory reset",
    category: "storage",
    runtime: "core-block",
    availability: "planned",
    appblocksId: "settings_init",
    typeId: "ab.settings_init",
    fields: [
      sel("mode", "Modalità", [
        { value: "defaults", label: "Valori di default" },
        { value: "factory", label: "Factory reset" },
      ], "defaults"),
    ],
    notes: AUTHORING,
  }),
  e({
    id: "appblocks.json_get_string",
    label: "JSON Get String",
    subtitle: "Estrai campo JSON",
    category: "storage",
    runtime: "core-block",
    availability: "planned",
    appblocksId: "json_get_string",
    typeId: "json_get_string",
    notes: "Solo path bounded e payload cap; JSON libero resta Node-RED.",
  }),

  e({
    id: "appblocks.ser_data_arrival",
    label: "On Serial Data Arrival",
    subtitle: "UART in ingresso",
    category: "serial",
    runtime: "core-event",
    availability: "planned",
    appblocksId: "ser_data_arrival",
    fields: [txt("port", "Porta", "")],
    notes: AUTHORING,
  }),
  e({
    id: "appblocks.sms_recv",
    label: "On SMS Received",
    subtitle: "SMS in ingresso",
    category: "serial",
    runtime: "core-event",
    availability: "planned",
    appblocksId: "sms_recv",
    needsModule: false,
    fields: [txt("from", "Filtro mittente", "")],
    notes: AUTHORING,
  }),
  e({
    id: "appblocks.ser_data_send",
    label: "Serial Data Send",
    subtitle: "UART in uscita",
    category: "serial",
    runtime: "core-block",
    availability: "planned",
    appblocksId: "ser_data_send",
    typeId: "ab.ser_data_send",
    fields: [txt("port", "Porta"), area("data", "Dati")],
    notes: AUTHORING,
  }),
  e({
    id: "appblocks.sms_send",
    label: "Send SMS",
    subtitle: "Invia SMS",
    category: "serial",
    runtime: "core-block",
    availability: "planned",
    appblocksId: "sms_send",
    typeId: "ab.sms_send",
    fields: [txt("to", "Numero"), area("message", "Messaggio")],
    notes: AUTHORING,
  }),

  e({
    id: "appblocks.network_changed",
    label: "On Network Changed",
    subtitle: "Cambio rete",
    category: "network",
    runtime: "core-event",
    availability: "planned",
    appblocksId: "network_changed",
    needsModule: false,
    fields: [
      sel("when", "Quando", [
        { value: "any", label: "Qualsiasi cambio" },
        { value: "up", label: "Connesso" },
        { value: "down", label: "Disconnesso" },
      ], "any"),
    ],
    notes: AUTHORING,
  }),
  e({
    id: "appblocks.socket_data_arrival",
    label: "On Socket Data",
    subtitle: "Socket RX",
    category: "network",
    runtime: "core-event",
    availability: "planned",
    appblocksId: "socket_data_arrival",
    needsModule: false,
    fields: [txt("socket", "Socket", "")],
    notes: AUTHORING,
  }),
  e({
    id: "appblocks.socket_event",
    label: "On Socket Event",
    subtitle: "Connect / drop",
    category: "network",
    runtime: "core-event",
    availability: "planned",
    appblocksId: "socket_event",
    needsModule: false,
    fields: [
      sel("event", "Evento", [
        { value: "connect", label: "Connesso" },
        { value: "disconnect", label: "Disconnesso" },
        { value: "error", label: "Errore" },
      ], "connect"),
    ],
    notes: AUTHORING,
  }),
  e({
    id: "appblocks.http_server_endpoint",
    label: "On HTTP Server Endpoint Called",
    subtitle: "Endpoint HTTP",
    category: "network",
    runtime: "core-event",
    availability: "planned",
    appblocksId: "http_server_endpoint",
    needsModule: false,
    fields: [
      sel("method", "Metodo", [
        { value: "GET", label: "GET" },
        { value: "POST", label: "POST" },
        { value: "PUT", label: "PUT" },
        { value: "DELETE", label: "DELETE" },
      ], "GET"),
      txt("path", "Percorso", "/"),
    ],
    notes: AUTHORING,
  }),
  e({
    id: "appblocks.socket_connect",
    label: "Socket Connect",
    subtitle: "Apri socket",
    category: "network",
    runtime: "core-block",
    availability: "planned",
    appblocksId: "socket_connect",
    typeId: "ab.socket_connect",
    fields: [txt("host", "Host"), num("port", "Porta", 80)],
    notes: AUTHORING,
  }),
  e({
    id: "appblocks.socket",
    label: "Socket Send",
    subtitle: "Invia su socket",
    category: "network",
    runtime: "core-block",
    availability: "planned",
    appblocksId: "socket",
    typeId: "ab.socket_send",
    fields: [txt("socket", "Socket", ""), area("data", "Dati")],
    notes: AUTHORING,
  }),
  e({
    id: "appblocks.http",
    label: "HTTP Request",
    subtitle: "Client HTTP",
    category: "network",
    runtime: "core-block",
    availability: "planned",
    appblocksId: "http",
    typeId: "ab.http_request",
    fields: [
      sel("method", "Metodo", [
        { value: "GET", label: "GET" },
        { value: "POST", label: "POST" },
        { value: "PUT", label: "PUT" },
        { value: "DELETE", label: "DELETE" },
      ], "GET"),
      txt("url", "URL"),
      area("body", "Body"),
    ],
    notes: AUTHORING,
  }),
  e({
    id: "appblocks.http_server_response",
    label: "HTTP Response",
    subtitle: "Risposta HTTP",
    category: "network",
    runtime: "node-red",
    availability: "unavailable",
    appblocksId: "http_server_response",
    notes: "Node-RED.",
  }),

  e({
    id: "appblocks.mqtt_sub",
    label: "MQTT Subscribe",
    subtitle: "MQTT in ingresso",
    category: "cloud",
    runtime: "core-event",
    availability: "planned",
    appblocksId: "mqtt_sub",
    needsModule: false,
    fields: [txt("topic", "Topic")],
    notes: AUTHORING,
  }),
  e({
    id: "appblocks.mqtt_change",
    label: "On MQTT Connected",
    subtitle: "Stato MQTT",
    category: "cloud",
    runtime: "core-event",
    availability: "planned",
    appblocksId: "mqtt_change",
    needsModule: false,
    fields: [
      sel("when", "Quando", [
        { value: "any", label: "Qualsiasi cambio" },
        { value: "connected", label: "Connesso" },
        { value: "disconnected", label: "Disconnesso" },
      ], "any"),
    ],
    notes: AUTHORING,
  }),
  e({
    id: "appblocks.mqtt_pub",
    label: "MQTT Publish",
    subtitle: "Pubblica su topic",
    category: "cloud",
    runtime: "core-block",
    availability: "shipped",
    appblocksId: "mqtt_pub",
    typeId: "publish_field",
    fields: [txt("topic", "Topic"), area("payload", "Payload")],
    notes: "Block firmware `publish_field`. Topic/payload visibili in authoring.",
  }),

  e({
    id: "appblocks.modbus_slave_register",
    label: "On Modbus Receive",
    subtitle: "Registro slave",
    category: "modbus",
    runtime: "core-event",
    availability: "unavailable",
    appblocksId: "modbus_slave_register",
    packId: "transport-modbus",
    notes: "Escluso da questa passata di authoring.",
  }),
  e({
    id: "appblocks.modbus_response",
    label: "On Modbus Response",
    subtitle: "Risposta master",
    category: "modbus",
    runtime: "core-event",
    availability: "unavailable",
    appblocksId: "modbus_response",
    packId: "transport-modbus",
    notes: "Escluso da questa passata di authoring.",
  }),
  e({
    id: "appblocks.modbus_timeout",
    label: "On Modbus Timeout",
    subtitle: "Timeout Modbus",
    category: "modbus",
    runtime: "core-event",
    availability: "unavailable",
    appblocksId: "modbus_timeout",
    packId: "transport-modbus",
    notes: "Escluso da questa passata di authoring.",
  }),
  e({
    id: "appblocks.modbus_write",
    label: "Modbus Request",
    subtitle: "Richiesta Modbus",
    category: "modbus",
    runtime: "core-rule",
    availability: "unavailable",
    appblocksId: "modbus_write",
    typeId: "threshold",
    packId: "transport-modbus",
    notes: "Escluso da questa passata di authoring.",
  }),

  e({
    id: "block.publish_field",
    label: "Publish field",
    subtitle: "Sink record",
    category: "cloud",
    runtime: "core-block",
    availability: "shipped",
    typeId: "publish_field",
    notes: "Stesso driver di MQTT Publish; voce nativa per chi cerca il type_id firmware.",
  }),
  e({
    id: "rule.threshold",
    label: "Rule soglia",
    subtitle: "Soglia → comando",
    category: "logic",
    runtime: "core-rule",
    availability: "shipped",
    typeId: "threshold",
    fields: [
      sel("op", "Quando la misura è", [
        { value: "gte", label: "≥  maggiore o uguale" },
        { value: "gt", label: ">  maggiore" },
        { value: "lte", label: "≤  minore o uguale" },
        { value: "lt", label: "<  minore" },
        { value: "eq", label: "=  uguale" },
      ], "gte"),
      { id: "level", label: "Soglia", type: "number", default: 0 },
      sel("action", "allora il GPIO", [
        { value: "high", label: "Va alto" },
        { value: "low", label: "Va basso" },
      ], "high"),
    ],
    notes: "Soglia firmware (campi 3/4/8). Il GPIO può solo andare alto o basso — non diventa input.",
  }),
];
