#include <spaghetti/capabilities.h>

#include <errno.h>
#include <stdint.h>

#include <zephyr/devicetree.h>
#include <zephyr/sys/util.h>

#include <spaghetti/resource_contract.h>

#if defined(CONFIG_SPAGHETTI_RESOURCE_PROFILE_MINIMAL)
#define SPAGHETTI_RESOURCE_PROFILE_VALUE \
	SPAGHETTI_RESOURCE_PROFILE_MINIMAL
#elif defined(CONFIG_SPAGHETTI_RESOURCE_PROFILE_STANDARD)
#define SPAGHETTI_RESOURCE_PROFILE_VALUE \
	SPAGHETTI_RESOURCE_PROFILE_STANDARD
#else
#define SPAGHETTI_RESOURCE_PROFILE_VALUE \
	SPAGHETTI_RESOURCE_PROFILE_EXTENDED
#endif

#define SPAGHETTI_REQUIRED_RECORD_CONSUMERS \
	(1U + IS_ENABLED(CONFIG_MQTT_LIB) + IS_ENABLED(CONFIG_BT))

#define SPAGHETTI_CAPABILITIES_BASE \
	((IS_ENABLED(CONFIG_BT) ? SPAGHETTI_BUILD_CAP_BLE : 0U) | \
	 (IS_ENABLED(CONFIG_WIFI) ? SPAGHETTI_BUILD_CAP_WIFI : 0U) | \
	 (IS_ENABLED(CONFIG_MQTT_LIB) ? SPAGHETTI_BUILD_CAP_MQTT : 0U) | \
	 (IS_ENABLED(CONFIG_SPAGHETTI_OTA_BLE) ? \
		SPAGHETTI_BUILD_CAP_OTA_BLE : 0U) | \
	 ((IS_ENABLED(CONFIG_WIFI) && \
	   IS_ENABLED(CONFIG_NET_SOCKETS_ENABLE_DTLS)) ? \
		SPAGHETTI_BUILD_CAP_OTA_WIFI : 0U) | \
	 (IS_ENABLED(CONFIG_SPAGHETTI_REMOTE_CONSOLE) ? \
		SPAGHETTI_BUILD_CAP_REMOTE_CONSOLE : 0U) | \
	 (IS_ENABLED(CONFIG_SPAGHETTI_HAS_EXTERNAL_RAM) ? \
		SPAGHETTI_BUILD_CAP_EXTERNAL_RAM : 0U) | \
	 (IS_ENABLED(CONFIG_SPAGHETTI_RUNTIME_PORT_MUX) ? \
		SPAGHETTI_BUILD_CAP_RUNTIME_PORT_MUX : 0U) | \
	 (IS_ENABLED(CONFIG_SPAGHETTI_POWER) ? \
		SPAGHETTI_BUILD_CAP_POWER_SWITCHING : 0U) | \
	 (IS_ENABLED(CONFIG_SPAGHETTI_POWER_MEASUREMENT) ? \
		SPAGHETTI_BUILD_CAP_POWER_MEASUREMENT : 0U) | \
	 (IS_ENABLED(CONFIG_SPAGHETTI_FIELD_UPDATE_CAN) ? \
		SPAGHETTI_BUILD_CAP_OTA_CAN : 0U) | \
	 (IS_ENABLED(CONFIG_SPAGHETTI_FIELD_UPDATE_ESPNOW) ? \
		SPAGHETTI_BUILD_CAP_OTA_ESPNOW : 0U))

#if defined(CONFIG_WATCHDOG) && DT_HAS_CHOSEN(zephyr_watchdog)
#define SPAGHETTI_HARDWARE_WATCHDOG_CAPABILITY \
	SPAGHETTI_BUILD_CAP_HARDWARE_WATCHDOG
#else
#define SPAGHETTI_HARDWARE_WATCHDOG_CAPABILITY 0U
#endif

BUILD_ASSERT(sizeof(CONFIG_SPAGHETTI_CORE_VARIANT) <=
	     SPAGHETTI_CORE_VARIANT_SIZE);
BUILD_ASSERT(CONFIG_SPAGHETTI_MAX_MODULES <= UINT16_MAX);
BUILD_ASSERT(CONFIG_SPAGHETTI_MAX_SCHEDULES <= UINT16_MAX);
BUILD_ASSERT(CONFIG_SPAGHETTI_MAX_RULES <= UINT16_MAX);
BUILD_ASSERT(CONFIG_SPAGHETTI_MAX_DEVICE_PROFILES <= UINT16_MAX);
BUILD_ASSERT(CONFIG_SPAGHETTI_MAX_PROFILE_OPERATIONS <= UINT16_MAX);
BUILD_ASSERT(CONFIG_SPAGHETTI_MAX_PROCESSING_BLOCKS <= UINT16_MAX);
BUILD_ASSERT(CONFIG_SPAGHETTI_MAX_PROCESSING_EDGES <= UINT16_MAX);
BUILD_ASSERT(CONFIG_SPAGHETTI_MAX_PROPERTIES_PER_SET <= UINT16_MAX);
BUILD_ASSERT(CONFIG_SPAGHETTI_MAX_PROTOCOL_PAYLOAD <= UINT16_MAX);
BUILD_ASSERT(CONFIG_SPAGHETTI_MAX_RECORD_QUEUE <= UINT16_MAX);
BUILD_ASSERT(CONFIG_SPAGHETTI_MAX_RECORD_CONSUMERS <= UINT8_MAX);
BUILD_ASSERT(CONFIG_SPAGHETTI_MAX_BLE_PEERS <= UINT8_MAX);
BUILD_ASSERT(CONFIG_SPAGHETTI_MAX_PRINCIPALS <= UINT8_MAX);
BUILD_ASSERT(CONFIG_SPAGHETTI_MAX_AUDIT_ENTRIES <= UINT8_MAX);
BUILD_ASSERT(CONFIG_SPAGHETTI_MAX_INFLIGHT_REQUESTS <= UINT8_MAX);
BUILD_ASSERT(CONFIG_SPAGHETTI_MAX_SECURE_SESSIONS <= UINT8_MAX);
BUILD_ASSERT(CONFIG_SPAGHETTI_MAX_FLOWS <= UINT8_MAX);
BUILD_ASSERT(CONFIG_SPAGHETTI_MAX_FUNCTION_BAYS_PER_FLOW <= UINT8_MAX);
BUILD_ASSERT(CONFIG_SPAGHETTI_MAX_POWER_RAILS <= UINT8_MAX);
BUILD_ASSERT(SPAGHETTI_RESOURCE_POWER_RAIL_MASK_VALID(
	CONFIG_SPAGHETTI_MAX_POWER_RAILS));
BUILD_ASSERT(SPAGHETTI_RESOURCE_SECURE_WORKSPACE_VALID(
	CONFIG_SPAGHETTI_MAX_SECURE_SESSIONS,
	CONFIG_SPAGHETTI_SECURE_WORKSPACE_SIZE));
BUILD_ASSERT(SPAGHETTI_RESOURCE_CONSUMERS_VALID(
	CONFIG_SPAGHETTI_MAX_RECORD_CONSUMERS,
	SPAGHETTI_REQUIRED_RECORD_CONSUMERS));
BUILD_ASSERT(!IS_ENABLED(CONFIG_SPAGHETTI_POWER_MEASUREMENT) ||
	     IS_ENABLED(CONFIG_SPAGHETTI_POWER));

static const struct spaghetti_capabilities capabilities = {
	.resource_profile = SPAGHETTI_RESOURCE_PROFILE_VALUE,
	.build_capabilities = SPAGHETTI_CAPABILITIES_BASE |
		SPAGHETTI_HARDWARE_WATCHDOG_CAPABILITY,
	.max_modules = CONFIG_SPAGHETTI_MAX_MODULES,
	.max_schedules = CONFIG_SPAGHETTI_MAX_SCHEDULES,
	.max_rules = CONFIG_SPAGHETTI_MAX_RULES,
	.max_device_profiles = CONFIG_SPAGHETTI_MAX_DEVICE_PROFILES,
	.max_profile_operations = CONFIG_SPAGHETTI_MAX_PROFILE_OPERATIONS,
	.max_processing_blocks = CONFIG_SPAGHETTI_MAX_PROCESSING_BLOCKS,
	.max_processing_edges = CONFIG_SPAGHETTI_MAX_PROCESSING_EDGES,
	.max_properties_per_set = CONFIG_SPAGHETTI_MAX_PROPERTIES_PER_SET,
	.max_protocol_payload = CONFIG_SPAGHETTI_MAX_PROTOCOL_PAYLOAD,
	.max_record_queue = CONFIG_SPAGHETTI_MAX_RECORD_QUEUE,
	.max_record_consumers = CONFIG_SPAGHETTI_MAX_RECORD_CONSUMERS,
	.max_ble_peers = CONFIG_SPAGHETTI_MAX_BLE_PEERS,
	.max_principals = CONFIG_SPAGHETTI_MAX_PRINCIPALS,
	.max_audit_entries = CONFIG_SPAGHETTI_MAX_AUDIT_ENTRIES,
	.max_inflight_requests = CONFIG_SPAGHETTI_MAX_INFLIGHT_REQUESTS,
	.max_secure_sessions = CONFIG_SPAGHETTI_MAX_SECURE_SESSIONS,
	.max_flows = CONFIG_SPAGHETTI_MAX_FLOWS,
	.max_function_bays_per_flow =
		CONFIG_SPAGHETTI_MAX_FUNCTION_BAYS_PER_FLOW,
	.max_power_rails = CONFIG_SPAGHETTI_MAX_POWER_RAILS,
	.replay_window_ms = CONFIG_SPAGHETTI_PROTOCOL_REPLAY_WINDOW_MS,
	.core_variant = CONFIG_SPAGHETTI_CORE_VARIANT,
};

int spaghetti_capabilities_get(struct spaghetti_capabilities *out)
{
	if (out == NULL) {
		return -EINVAL;
	}

	*out = capabilities;
	return 0;
}

bool spaghetti_capabilities_support(uint32_t required)
{
	return (capabilities.build_capabilities & required) == required;
}
