import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { createHub } from '../src/server.mjs';
import { openStore } from '../src/store.mjs';

test('catalog, protected uploads, publishing, voting, contests and push synchronization', async (t) => {
  const directory = await mkdtemp(path.join(tmpdir(), 'spaghetti-hub-'));
  const hub = await createHub({ directory, adminToken: 'test-admin-token', allowLocalAdmin: false });
  await new Promise((resolve) => hub.server.listen(0, '127.0.0.1', resolve));
  const base = `http://127.0.0.1:${hub.server.address().port}`;
  t.after(async () => { hub.server.closeAllConnections(); await new Promise((resolve) => hub.server.close(resolve)); await rm(directory, { recursive: true, force: true }); });
  const call = (route, method = 'GET', data, token) => fetch(`${base}/api/v1/${route}`, { method, headers: { ...(token ? { authorization: `Bearer ${token}` } : {}), ...(data === undefined ? {} : { 'content-type': 'application/json' }) }, body: data === undefined ? undefined : JSON.stringify(data) });
  const initial = await (await call('sync')).json();
  assert.equal(initial.modules.length, 2);
  assert.equal(initial.users, undefined);
  assert.equal((await fetch(`${base}/api/v1/sync`, { headers: { 'if-none-match': `"${initial.revision}"` } })).status, 304);
  assert.equal((await call('admin/state')).status, 401);
  assert.equal((await call('auth/local-admin', 'POST', {})).status, 403);
  assert.equal((await call('admin/posts', 'POST', {}, 'é'.repeat(16))).status, 401);
  const bytes = Buffer.from('firmware test artifact');
  const uploaded = await fetch(`${base}/api/v1/admin/uploads`, { method: 'POST', headers: { authorization: 'Bearer test-admin-token', 'x-filename': 'firmware.bin' }, body: bytes });
  assert.equal(uploaded.status, 201);
  const file = await uploaded.json();
  assert.equal(file.sha256, createHash('sha256').update(bytes).digest('hex'));
  assert.equal((await call(`files/${file.id}`)).status, 404);
  const events = await fetch(`${base}/api/v1/events`);
  const reader = events.body.getReader();
  await reader.read();
  const release = await (await call('admin/packages', 'POST', { title: 'Firmware', description: 'Test', kind: 'firmware', version: '1.0', target: 'test', published: true, fileId: file.id }, 'test-admin-token')).json();
  const pushed = new TextDecoder().decode((await reader.read()).value);
  assert.match(pushed, /event: sync/);
  assert.match(pushed, /save-packages/);
  await reader.cancel();
  const downloaded = await call(`files/${file.id}`);
  assert.match(downloaded.headers.get('content-disposition'), /attachment/);
  assert.deepEqual(Buffer.from(await downloaded.arrayBuffer()), bytes);
  const duplicate = { title: 'Duplicate', registryId: initial.modules[0].registryId, vendorId: initial.modules[0].vendorId, moduleTypeId: initial.modules[0].moduleTypeId };
  assert.equal((await call('admin/modules', 'POST', duplicate, 'test-admin-token')).status, 409);
  assert.equal((await call('admin/modules', 'POST', { title: 'Invalid I2C', registryId: 9, vendorId: 9, moduleTypeId: 9, modes: [4, 5, 4, 0], pins: ['5V', 'SDA', 'SCL', 'SDA', 'NC', 'GND'] }, 'test-admin-token')).status, 400);
  const register = await call('auth/register', 'POST', { username: 'maker', password: 'long-test-password', displayName: 'Maker' });
  const account = await register.json();
  assert.equal(register.status, 200);
  assert.equal((await call(`polls/${initial.polls[0].id}/vote`, 'POST', { option: 0 }, account.token)).status, 200);
  assert.equal((await call(`polls/${initial.polls[0].id}/vote`, 'POST', { option: 1 }, account.token)).status, 200);
  let snapshot = await (await call('sync')).json();
  assert.deepEqual(snapshot.polls[0].counts, [0, 1, 0]);
  assert.equal((await call(`admin/polls/${initial.polls[0].id}`, 'PUT', { ...initial.polls[0], options: ['Different', 'Choices'] }, 'test-admin-token')).status, 409);
  const submissionData = { title: 'My project', description: 'Private description', projectUrl: 'https://example.org/project' };
  const submitted = await call(`contests/${initial.contests[0].id}/submissions`, 'POST', submissionData, account.token);
  const submission = await submitted.json();
  assert.equal(submitted.status, 201);
  assert.equal((await call(`contests/${initial.contests[0].id}/submissions`, 'POST', submissionData, account.token)).status, 409);
  assert.equal((await call('admin/awards', 'POST', { submissionId: submission.id, prize: 'A new module' }, 'test-admin-token')).status, 201);
  snapshot = await (await call('sync')).json();
  assert.equal(snapshot.contests[0].awards[0].winner, 'Maker');
  assert.equal(JSON.stringify(snapshot).includes('Private description'), false);
  assert.equal((await call(`admin/packages/${release.id}`, 'DELETE', undefined, 'test-admin-token')).status, 200);
  assert.equal((await call(`files/${file.id}`)).status, 404);
});

test('atomic store serializes writes, rolls back errors and survives reopening', async (t) => {
  const directory = await mkdtemp(path.join(tmpdir(), 'spaghetti-store-'));
  t.after(() => rm(directory, { recursive: true, force: true }));
  const store = await openStore(directory, { schemaVersion: 1, revision: 1, values: [] });
  await Promise.all(Array.from({ length: 20 }, (_, index) => store.change((data) => { data.values.push(index); })));
  await assert.rejects(store.change((data) => { data.values.push('bad'); throw new Error('abort'); }));
  assert.equal(store.read().values.length, 20);
  assert.equal((await openStore(directory, {})).read().revision, 21);
});
